steps:
  # 1. Build the Container Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/talma-repo/backend:$COMMIT_SHA', '.']

  # 2. Push the Image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/talma-repo/backend:$COMMIT_SHA']

  # 3. Deploy API Service to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'talma-backend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/talma-repo/backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      # Replaces environment variables with those defined in trigger or uses existing
      # Ensure you set DB/Redis/Secret vars in Cloud Run console once, or use --update-env-vars here

  # 4. Deploy Celery Worker Service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'talma-worker'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/talma-repo/backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--no-cpu-throttling'
      - '--command'
      - 'celery'
      - '--args'
      - '-A,core.celery.celery_app.celery_app,worker,--loglevel=info,--pool=threads,--concurrency=20,-Q,document_queue,celery'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/talma-repo/backend:$COMMIT_SHA'
