steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/talma-repo/backend:$COMMIT_SHA', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/talma-repo/backend:$COMMIT_SHA']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'talma-backend'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/talma-repo/backend:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--update-env-vars'
      - 'SERVICE_TYPE=api'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'talma-celery'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/talma-repo/backend:$COMMIT_SHA'
      - '--port'
      - '8080'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--no-allow-unauthenticated'
      - '--min-instances'
      - '1'
      - '--no-cpu-throttling'
      - '--update-env-vars'
      - 'SERVICE_TYPE=worker'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/talma-repo/backend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY